import type { HomeCategory } from '../type/category';

/** หมวดหมู่หน้าแรก — ลิงก์ไปหน้าจัดอันดับ/ค้นหา · รูปอยู่ public/images/categories */
export const CATEGORIES: HomeCategory[] = [
  {
    key: 'pub',
    image: '/images/categories/edm-dance-floor.webp',
    title: 'ผับ / บาร์',
    subtitle: 'แดนซ์ ปาร์ตี้',
    to: '/ranking?category=PUB_BAR',
  },
  {
    key: 'chill',
    image: '/images/categories/intimate-cocktail-bar.webp',
    title: 'นั่งชิล',
    subtitle: 'คุยกันยาว ๆ',
    to: '/ranking?category=CHILL',
  },
  {
    key: 'food',
    image: '/images/categories/friends-at-dinner.webp',
    title: 'ร้านอาหาร',
    subtitle: 'กินจริงจัง',
    to: '/ranking?category=RESTAURANT',
  },
  {
    key: 'live',
    image: '/images/categories/live-music-dinner.webp',
    title: 'ดนตรีสด',
    subtitle: 'วงเล่นทุกคืน',
    to: '/search?style=Live%20Music',
  },
  {
    key: 'rooftop',
    image: '/images/categories/rooftop-lounge-skyline.webp',
    title: 'Rooftop',
    subtitle: 'วิวเมือง',
    to: '/search?style=Rooftop',
  },
  {
    key: 'quiet',
    image: '/images/categories/vinyl-listening-bar.webp',
    title: 'ร้านเงียบ',
    subtitle: 'คุยงานได้',
    to: '/search?style=Quiet',
  },
  {
    key: 'outdoor',
    image: '/images/categories/outdoor-garden-dinner.webp',
    title: 'Outdoor',
    subtitle: 'นั่งรับลม',
    to: '/search?style=Outdoor',
  },
  {
    key: 'private',
    image: '/images/categories/candlelit-dinner-date.webp',
    title: 'ห้องส่วนตัว',
    subtitle: 'มากันเป็นกลุ่ม',
    to: '/search?style=Private%20Room',
  },
  {
    key: 'beer',
    image: '/images/categories/beer-pour.webp',
    title: 'เบียร์',
    subtitle: 'ชิล ๆ สักแก้ว',
    to: '/search?style=Beer',
  },
  {
    key: 'cocktail',
    image: '/images/categories/orange-cocktail-splash.webp',
    title: 'Cocktail',
    subtitle: 'จิบสีสวย',
    to: '/search?style=Cocktail',
  },
  {
    key: 'wine',
    image: '/images/categories/red-wine-pour.webp',
    title: 'Wine',
    subtitle: 'ดินเนอร์ละมุน',
    to: '/search?style=Wine',
  },
  {
    key: 'whisky',
    image: '/images/categories/whisky-on-the-rocks.webp',
    title: 'Whisky',
    subtitle: 'นั่งจิบช้า ๆ',
    to: '/search?style=Whisky',
  },
  {
    key: 'sake',
    image: '/images/categories/sake-set.webp',
    title: 'Sake',
    subtitle: 'ญี่ปุ่นสไตล์',
    to: '/search?style=Sake',
  },
  {
    key: 'shot',
    image: '/images/categories/rainbow-shot.webp',
    title: 'Shot',
    subtitle: 'ชนแก้วให้สุด',
    to: '/search?style=Shot',
  },
  {
    key: 'soju',
    image: '/images/categories/soju-bottle-and-cup.webp',
    title: 'Soju',
    subtitle: 'เกาหลีสายชิล',
    to: '/search?style=Soju',
  },
  {
    key: 'speakeasy',
    image: '/images/categories/rooftop-cocktail-lounge.webp',
    title: 'Speakeasy',
    subtitle: 'บาร์ลับน่าค้นหา',
    to: '/search?style=Speakeasy',
  },
  {
    key: 'clubs',
    image: '/images/categories/nightclub-entrance.webp',
    title: 'Clubs & Events',
    subtitle: 'คืนที่มีสีสัน',
    to: '/search?style=Clubs%20%26%20Events',
  },
  {
    key: 'craft-beer',
    image: '/images/categories/friends-beer-toast.webp',
    title: 'Craft Beer',
    subtitle: 'เบียร์ทำมือ',
    to: '/search?style=Craft%20Beer',
  },
  {
    key: 'rooftop-bar',
    image: '/images/categories/couple-arriving-at-rooftop.webp',
    title: 'Rooftop Bar',
    subtitle: 'วิวเมืองยามค่ำ',
    to: '/search?style=Rooftop%20Bar',
  },
  {
    key: 'korean',
    image: '/images/categories/friends-dinner-toast.webp',
    title: 'Korean Pop',
    subtitle: 'สังสรรค์สไตล์เกาหลี',
    to: '/search?style=Korean%20Pop',
  },
  {
    key: 'japanese',
    image: '/images/categories/woman-at-cocktail-bar.webp',
    title: 'Japanese Bar',
    subtitle: 'บาร์ญี่ปุ่นร่วมสมัย',
    to: '/search?style=Japanese%20Bar',
  },
  {
    key: 'party',
    image: '/images/categories/night-out-group-toast.webp',
    title: 'Party & Dancing',
    subtitle: 'สายปาร์ตี้ตัวจริง',
    to: '/search?style=Party%20%26%20Dancing',
  },
  {
    key: 'date-night',
    image: '/images/categories/sunset-rooftop-date.webp',
    title: 'Date Night',
    subtitle: 'ค่ำคืนของเรา',
    to: '/search?style=Date%20Night',
  },
  {
    key: 'walking-street',
    image: '/images/categories/rainy-night-street.webp',
    title: 'Walking Street',
    subtitle: 'ถนนคนเดินยามค่ำ',
    to: '/search?style=Walking%20Street',
  },
];

/** สีชื่อหมวดบนการ์ด (ตาม key) */
export const CATEGORY_TEXT_COLORS: Record<string, string> = {
  pub: '#F4B7FF',
  chill: '#FFD166',
  food: '#FFCF70',
  live: '#FFC857',
  rooftop: '#E9C2FF',
  quiet: '#F2B56B',
  outdoor: '#FFD166',
  private: '#FFB6C1',
  beer: '#F4D35E',
  cocktail: '#FFB347',
  wine: '#F2A7BB',
  whisky: '#D9A066',
  sake: '#E8D3A8',
  shot: '#FF9BD2',
  soju: '#9FE870',
  speakeasy: '#E9B872',
  clubs: '#FF8FD8',
  'craft-beer': '#FFD166',
  'rooftop-bar': '#F0C4FF',
  korean: '#FF9A76',
  japanese: '#FFC1A1',
  party: '#FF91C8',
  'date-night': '#FFB4A2',
  'walking-street': '#F7C873',
};
